### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/tcl#1]
Edit this issue to keep track of the tasks you're working on towards launch.

We have a rough guide for how to launch a track, which is a good starting point;
please ask if you have any questions or if anything is confusing!
https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

This you might consider for the exercises (test suites and code examples) in this
track. Open separate issues for the ones you wish to implement.

- Is there a style guide for Tcl?
- Are these styles encouraged or enforced?
- Are there any conventions that we should adopt on this track for the sake of consistency?
- Can we enforce these?
- Is there a linter? Are there many? Should we use one?
- Is there a common convention for filenames? If not, what should our convention be?

Once you've gotten the track into a state where others can contribute, update the
README to reflect the choices you've made and provide guidelines for contribution.

**Comment by sshine** [comment]
Answering these questions here for consistency, the launch process is continued in #3.

## Style guide resources

- https://www.tcl.tk/doc/styleGuide.pdf (only widely distributed)
- https://www.tcl.tk/doc/engManual.pdf (C style guide for Tcl interop)
- https://www.gidhome.com/ManHtml/HowTo/resource/namespaces.html (extension to style guide)
- https://wiki.tcl-lang.org/page/Tcl+style+discussion (discussion)

I don't intend to include any of these resources. The widely published style guide covers:

- basic language-independent styling like proper indentation, naming
- using namespaces and organizing large-scale applications
- testing and organizing tests in files
- a few Tcl-specific hints, like "Don't use `then`, but do use `else`".

Although it is an excellent document, I don't think it covers enough Tcl-specific style-related points to make this recommended reading before solving exercises. Most of its concerns don't apply in the context of a single-file exercise.

At the syntax level, Tcl can be written in a lot of dangerous ways (e.g. overriding all elementary language constructs, or self-modifying code, like in Lisp), but the style guide doesn't address this in particular.

I'd like to revise this answer once the track has gotten some traffic, or someone interjects.

## Linter

[The Tcler's Wiki](https://wiki.tcl-lang.org/page/Tcl+Lint) provides a single broken link to a commercial project.

I'd say no.

## Filename convention

I'd suggest "exercise-name.tcl" since it maps 1-to-1 with the slug.
