### ISSUE TITLE
Name of test file

### ISSUE THREAD

**Issue by glennj** [exercism/tcl#16]
From what I've read, it seems the standard way to name a test file is the rootname of the tcl file being tested plus a ".test" extension

Should we follow this convention?
```
exercises/
├── hello-world
│   ├── hello-world.tcl
│   └── hello-world.test
└── two-fer
    ├── two-fer.tcl
    └── two-fer.test
```

References:
* the [default configuration for `tcltest`](https://www.tcl-lang.org/man/tcl/TclCmd/tcltest.htm#M112)
* an ancient style guide, https://core.tcl-lang.org/tips/doc/trunk/tip/352.md
* [Getting Started with tcltest](https://wuhrr.wordpress.com/2011/03/28/getting-started-with-tcltest/)

**Comment by sshine** [comment]
I totally agree with this proposal.

Let's rename the files when #14 is merged.

**Comment by sshine** [comment]
- [ ] When we do this, update [`docs/TESTS.md`](https://github.com/exercism/tcl/blob/master/docs/TESTS.md) to reflect this change.
- [ ] To make this description propagate to the handout text (how to test isn't mentioned in the README at all yet), update [`config/exercise_readme.go.tmpl`](https://github.com/exercism/tcl/blob/master/config/exercise_readme.go.tmpl) with the same text. Because the message depends on the exercise's slug name, these are the variables available:

```bash
all-tracks $ grep -Proh '\.Spec\.\S*' * | sort -u
.Spec.Credits
.Spec.Description
.Spec.MixedCaseName
.Spec.Name
.Spec.Slug
.Spec.SnakeCaseName
```

**Comment by sshine** [comment]
- [ ] Update `config.json`'s `test_pattern` to `\.test$`
