### ISSUE TITLE
style for declaring instance variables for OO tcl

### ISSUE THREAD

**Issue by glennj** [exercism/tcl#50]
I recently discovered I may not be writing idiomatic OO tcl.

These two styles both seem to work equivalently:
```tcl
oo::class create Foo {
    variable bar

    constructor {input} {
        set bar $input
    }

    method twoBar {} {
        return [expr {2 * $bar}]
    }
}
```
and
```tcl
oo::class create Foo {
    constructor {input} {
        variable bar
        set bar $input
    }

    method twoBar {} {
        my variable bar
        return [expr {2 * $bar}]
    }
}
```

I don't why there the `my variable` is not required for the first style: I've [asked on StackOverflow](https://stackoverflow.com/q/58071069/7552).

While waiting for answers there, does one of those style strike you as "better"?

**Comment by sshine** [comment]
I've honestly not given it much thought. When OO functionality in Tcl is tacked on, I feel like this is more a debate of how to design OO layers, rather than what's idiomatic. I doubt anything is. If this were Perl, it'd be the Moose vs. default OO.

Judging from the SO answer by Donal Fellows, the 1st one seems to have the most intentional semantics. From a syntax perspective, I think you should decide what you like better.

**Comment by glennj** [comment]
closing
